const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.Fade,
		C3.Behaviors.Flash,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Text.Cnds.PickByUID,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Mouse.Cnds.OnAnyClick,
		C3.Plugins.Text.Acts.Destroy,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Browser.Cnds.IsFullscreen,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Text.Acts.SetFontFace,
		C3.Plugins.Text.Acts.TypewriterText,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Mouse.Acts.SetCursor2,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{Keyboard: 0},
	{Mouse: 0},
	{Browser: 0},
	{Cases_WhiteBoard: 0},
	{GitHub_Window: 0},
	{GitHub_Window_ButtonNO: 0},
	{GitHub_Window_ButtonYES: 0},
	{GitHub_Window_Text: 0},
	{GitHub_Window_DarkBG: 0},
	{Cursor_Classic: 0},
	{Угасание: 0},
	{Intro_APGOVProjectbyDaniil: 0},
	{Мигание: 0},
	{Intro_PressFandEnter: 0},
	{Intro_BG: 0},
	{Buttons_MainMenu_Cheats: 0},
	{Buttons_MainMenu_GuessTheImage: 0},
	{Buttons_MainMenu_Play: 0},
	{Buttons_MainMenu_Settings: 0},
	{Buttons_MainMenu_Skins: 0},
	{MainMenu_BG: 0},
	{MainMenu_Text: 0},
	{Icon_Github: 0},
	{Cases_BG: 0},
	{Buttons_Cheats_Back: 0},
	{Cheats_PreviousCase: 0},
	{Cheats_NextCase: 0},
	{Text_Cheats_Title: 0},
	{Text_Cheats_Body: 0},
	{Text_Cheats_Title2: 0},
	{Image1: 0},
	{Clickable: 0},
	{Cases: 0},
	{Cases2: 0}
];

self.InstanceType = {
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Cases_WhiteBoard: class extends self.ISpriteInstance {},
	GitHub_Window: class extends self.ISpriteInstance {},
	GitHub_Window_ButtonNO: class extends self.ISpriteInstance {},
	GitHub_Window_ButtonYES: class extends self.ISpriteInstance {},
	GitHub_Window_Text: class extends self.ITextInstance {},
	GitHub_Window_DarkBG: class extends self.ISpriteInstance {},
	Cursor_Classic: class extends self.ISpriteInstance {},
	Intro_APGOVProjectbyDaniil: class extends self.ITextInstance {},
	Intro_PressFandEnter: class extends self.ITextInstance {},
	Intro_BG: class extends self.ISpriteInstance {},
	Buttons_MainMenu_Cheats: class extends self.ISpriteInstance {},
	Buttons_MainMenu_GuessTheImage: class extends self.ISpriteInstance {},
	Buttons_MainMenu_Play: class extends self.ISpriteInstance {},
	Buttons_MainMenu_Settings: class extends self.ISpriteInstance {},
	Buttons_MainMenu_Skins: class extends self.ISpriteInstance {},
	MainMenu_BG: class extends self.ISpriteInstance {},
	MainMenu_Text: class extends self.ITextInstance {},
	Icon_Github: class extends self.ISpriteInstance {},
	Cases_BG: class extends self.ISpriteInstance {},
	Buttons_Cheats_Back: class extends self.ISpriteInstance {},
	Cheats_PreviousCase: class extends self.ISpriteInstance {},
	Cheats_NextCase: class extends self.ISpriteInstance {},
	Text_Cheats_Title: class extends self.ITextInstance {},
	Text_Cheats_Body: class extends self.ITextInstance {},
	Text_Cheats_Title2: class extends self.ITextInstance {},
	Image1: class extends self.ISpriteInstance {},
	Clickable: class extends self.ISpriteInstance {}
}